---
queue: bazel-lib
env:
  CC: /bin/false
workspaces:
  - .
  - e2e/smoke:
      gazelle:
        without: true
  - e2e/coreutils:
      gazelle:
        without: true
  - e2e/copy_to_directory:
      gazelle:
        without: true
  - e2e/external_copy_to_directory:
      gazelle:
        without: true
bazel:
  flags:
    - --remote_download_minimal
    - --nobuild_runfile_links
tasks:
  branch_freshness:
  gazelle:
  test:
